{% set name = "traceml" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/traceml-{{ version }}.tar.gz
    sha256: bceb8a811bc787021c8507f8cb2ac4e0523497e817cdfa030bf4b52901fbd875

build:
  noarch: python
  script:
    - mkdir requirements
    - mv requirements_dev.txt requirements/dev.txt
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest
    - python >=3.5
  run:
    - python >=3.5

test:
  imports:
    - traceml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/polyaxon/traceml
  summary: Engine for ML/Data tracking, visualization, dashboards, and model UI for Polyaxon.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
