{% set name = "traceml" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/traceml-{{ version }}.tar.gz
    sha256: da0d137c49667cad9d1c856fb481d7bde4c287ac46b5f466015aaaee0f84e001
  # Remove with the next release
  - url: https://raw.githubusercontent.com/polyaxon/traceml/7e13f469a08aee289c0d63e5b208b4cc3eb2781c/LICENSE
    sha256: fcf20c5d52bca6e95551cd3e75c20af556eac7f563a77e1caec0441bf1ffd095
    fn: LICENSE
  - url: https://raw.githubusercontent.com/polyaxon/traceml/7e13f469a08aee289c0d63e5b208b4cc3eb2781c/traceml/requirements/dev.txt
    sha256: aa7d382fdfa94b732a3b3447460c0130962d0e89ac76dfb4a0062f2fbc04e812
    fn: requirements_dev.txt

build:
  noarch: python
  script:
    - mkdir requirements
    - mv requirements_dev.txt requirements/dev.txt
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - traceml
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/polyaxon/traceml
  summary: Engine for ML/Data tracking, visualization, dashboards, and model UI for Polyaxon.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
